version: '3'

services:
  django_app:
    build: ./social_media
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/social_media
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./social_media:/app

  flask_likes:
    build: ./social_media_likes
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/social_media
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./social_media_likes:/app

  frontend:
    build:
      context: ./social_media_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./social_media_frontend:/app
    depends_on:
      - django_app
      - flask_likes

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_media
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: